import Head from "next/head";
import { getSession } from "next-auth/react";

export default function Home(props) {
  const { userData, session } = props;

  return (
    <>
      <Head>
        <title>GeoRent</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen items-center justify-center">
        {session?.user ? (
          <h1 className="text-4xl text-black">
            {" "}
            Welcome username: {userData.name}
          </h1>
        ) : (
          <h1 className="text-4xl text-black">Home</h1>
        )}
      </div>
    </>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  if (!session) return { props: {} };
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/auth/user`, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${session.user.jwt}`,
    },
  });
  const userData = await res.json();
  return {
    props: {
      userData,
      session,
    },
  };
}
