import Head from "next/head";
import { useSession } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>GeoRent</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen items-center justify-center">
        {session?.user ? (
          <h1 className="text-4xl text-black">
            {" "}
            Welcome username id: {session.user.name}
          </h1>
        ) : (
          <h1 className="text-4xl text-black">Home</h1>
        )}
      </div>
    </>
  );
}
